stages:
  - build

variables:
  CGO_ENABLED: 0
  GIT_DEPTH: 0


build binary:
  stage: build
  image: public.ecr.aws/docker/library/golang:1.26.0

  script:
    - go env -w GOPROXY=https://goproxy.cn,direct
    - GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o  ssh_forward .
  artifacts:
    paths:
      - ssh_forward


